"""add_report_feedback

Revision ID: 60f9534c7f72
Revises: 211cc7326b18
Create Date: 2025-12-15 21:27:12.945328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60f9534c7f72'
down_revision: Union[str, Sequence[str], None] = '211cc7326b18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rentals', sa.Column('issue_report', sa.String(), nullable=True))
    op.add_column('rentals', sa.Column('rating', sa.Integer(), nullable=True))
    op.add_column('rentals', sa.Column('feedback', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rentals', 'feedback')
    op.drop_column('rentals', 'rating')
    op.drop_column('rentals', 'issue_report')
    # ### end Alembic commands ###
