/**
 * Global Configuration & Localization
 */

const CONFIG = {
    PROJECT_NAME: "[NAME]", // Placeholder as requested
    DEFAULT_LANG: 'uk',     // Ukrainian by default
    API_BASE: "http://127.0.0.1:8000" // Default dev API
};

const TRANSLATIONS = {
    "uk": {
        "app_subtitle": "ПАНЕЛЬ КЕРУВАННЯ",
        "tab_login": "ВХІД",
        "tab_register": "РЕЄСТРАЦІЯ",
        "system_link": "АБО УВІЙТИ ЧЕРЕЗ",
        "label_callsign": "ЕЛЕКТРОННА ПОШТА",
        "label_security_key": "ПАРОЛЬ",
        "label_pilot_name": "ІМ'Я КОРИСТУВАЧА",
        "btn_login": "УВІЙТИ",
        "btn_register": "ЗАРЕЄСТРУВАТИСЯ",
        "auto_connect": "Запам'ятати мене",
        "lost_key": "Забули пароль?",
        "terms": "Реєструючись, ви погоджуєтесь з умовами використання.",
        "error_signal_lost": "Помилка з'єднання",
        "auth_authenticating": "Перевірка даних...",
        "auth_creating": "Створення акаунту...",
        "auth_failed": "Невірні дані",
        "reg_failed": "Помилка реєстрації",
        "google_failed": "Помилка Google Auth",
        "placeholder_email": "user@example.com",
        "placeholder_pass": "••••••••",
        "placeholder_name": "User Name",
        "hero_subtitle": "Керуйте FPV дронами дистанційно з професійною точністю",
        "btn_get_started": "РОЗПОЧАТИ",
        "btn_view_fleet": "ОГЛЯД ПРИСТРОЇВ",
        "landing_title": "Ласкаво просимо",
        "error_invalid_email": "Невірний формат пошти",
        "error_password_short": "Пароль має бути мінімум 8 символів",
        "error_email_taken": "Ця пошта вже зареєстрована",
        "pass_strength_weak": "Слабкий",
        "pass_strength_medium": "Середній",
        "pass_strength_strong": "Надійний",
        "forgot_title": "Відновлення пароля",
        "forgot_desc": "Введіть пошту, щоб отримати код",
        "btn_send_code": "НАДІСЛАТИ КОД",
        "verify_title": "Перевірка",
        "verify_desc": "Введіть код з email",
        "label_code": "КОД ПІДТВЕРДЖЕННЯ",
        "placeholder_code": "123456",
        "btn_verify": "ПІДТВЕРДИТИ",
        "reset_title": "Новий пароль",
        "reset_desc": "Створіть новий пароль",
        "btn_reset": "ЗМІНИТИ ПАРОЛЬ",
        "back_to_login": "Назад до входу",
        "code_sent": "Код надіслано!",
        "pass_updated": "Пароль оновлено!",
        "error_user_not_found": "Користувача не знайдено",
        "error_invalid_code": "Невірний код",
        "error_wrong_password": "Невірний пароль",
        "error_login_failed": "Помилка входу. Перевірте дані.",
        "error_network": "Помилка мережі. Спробуйте пізніше.",
        "Invalid credentials": "Невірна пошта або пароль",
        "User not found": "Користувача не знайдено"
    },
    "en": {
        "app_subtitle": "CONTROL PANEL",
        "tab_login": "LOGIN",
        "tab_register": "REGISTER",
        "system_link": "OR LOGIN WITH",
        "label_callsign": "EMAIL ADDRESS",
        "label_security_key": "PASSWORD",
        "label_pilot_name": "FULL NAME",
        "btn_login": "SIGN IN",
        "btn_register": "CREATE ACCOUNT",
        "auto_connect": "Remember me",
        "lost_key": "Forgot password?",
        "terms": "By registering, you agree to the Terms of Service.",
        "error_signal_lost": "Connection Error",
        "auth_authenticating": "Verifying...",
        "auth_creating": "Creating Account...",
        "auth_failed": "Invalid Credentials",
        "reg_failed": "Registration Failed",
        "google_failed": "Google Auth Failed",
        "placeholder_email": "user@example.com",
        "placeholder_pass": "••••••••",
        "placeholder_name": "User Name",
        "hero_subtitle": "Control FPV drones remotely with professional precision",
        "btn_get_started": "GET STARTED",
        "btn_view_fleet": "VIEW DEVICES",
        "landing_title": "Welcome",
        "error_invalid_email": "Invalid Email Format",
        "error_password_short": "Password must be at least 8 characters",
        "error_email_taken": "Email is already registered",
        "pass_strength_weak": "Weak",
        "pass_strength_medium": "Medium",
        "pass_strength_strong": "Strong",
        "forgot_title": "Recovery",
        "forgot_desc": "Enter email to receive code",
        "btn_send_code": "SEND CODE",
        "verify_title": "Verification",
        "verify_desc": "Enter code from email",
        "label_code": "VERIFICATION CODE",
        "placeholder_code": "123456",
        "btn_verify": "VERIFY",
        "reset_title": "New Password",
        "reset_desc": "Create a new password",
        "btn_reset": "UPDATE PASSWORD",
        "back_to_login": "Back to Login",
        "code_sent": "Code sent!",
        "pass_updated": "Password updated!",
        "error_user_not_found": "User not found",
        "error_invalid_code": "Invalid Code"
    }
};

window.CONFIG = CONFIG;
window.TRANSLATIONS = TRANSLATIONS;
